# Generated by Django 4.1.5 on 2023-02-07 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmacia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rede", models.CharField(max_length=250, verbose_name="Rede")),
                ("cnpj", models.CharField(max_length=250, verbose_name="CNPJ")),
                ("cep", models.CharField(max_length=250, verbose_name="CEP")),
                ("endereco", models.CharField(max_length=250, verbose_name="Endereço")),
                ("latitude_cep", models.FloatField(verbose_name="Latitude")),
                ("longitude_cep", models.FloatField(verbose_name="Longitude")),
                ("telefone", models.CharField(max_length=250, verbose_name="Telefone")),
                ("email", models.CharField(max_length=250, verbose_name="E-mail")),
                ("site", models.CharField(max_length=250, verbose_name="Site")),
                (
                    "registro_ms",
                    models.CharField(max_length=250, verbose_name="Registro MS"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado Em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Alteração"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Nome"
                    ),
                ),
                (
                    "nome_comercial",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Nome Comercial",
                    ),
                ),
                (
                    "indicacao",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Indicação"
                    ),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Unidade de Medida",
                    ),
                ),
                (
                    "valor_medida",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Valor da Medida"
                    ),
                ),
                (
                    "principio_ativo",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Princípio Ativo",
                    ),
                ),
                (
                    "dosagem",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Dosagem"
                    ),
                ),
                (
                    "preco",
                    models.FloatField(blank=True, null=True, verbose_name="Preço"),
                ),
                (
                    "gratuito",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Gratuito?"
                    ),
                ),
                (
                    "desconto",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Tem desconto?"
                    ),
                ),
                (
                    "porcentagem_desconto",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Porcentagem de Desconto"
                    ),
                ),
                (
                    "feedback_positivos",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Feedbacks Positivos"
                    ),
                ),
                (
                    "feedback_negativos",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Feedbacks Negativos"
                    ),
                ),
                (
                    "registro_ms",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Registro MS",
                    ),
                ),
                (
                    "codigo_de_barras",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Código de Barras",
                    ),
                ),
                (
                    "classificacao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Classificação"
                    ),
                ),
                (
                    "esta_ativo",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Está ativo?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado Em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Última Alteração"
                    ),
                ),
                (
                    "farmacia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmacia.farmacia",
                        verbose_name="Nome da Farmácia",
                    ),
                ),
            ],
        ),
    ]
