# Generated by Django 4.1.5 on 2023-02-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="medicamento", name="desconto",),
        migrations.RemoveField(model_name="medicamento", name="feedback_negativos",),
        migrations.RemoveField(model_name="medicamento", name="feedback_positivos",),
        migrations.RemoveField(model_name="medicamento", name="gratuito",),
        migrations.RemoveField(model_name="medicamento", name="porcentagem_desconto",),
        migrations.RemoveField(model_name="medicamento", name="preco",),
        migrations.CreateModel(
            name="Preco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco",
                    models.FloatField(blank=True, null=True, verbose_name="Preço"),
                ),
                (
                    "gratuito",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Gratuito?"
                    ),
                ),
                (
                    "desconto",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Tem desconto?"
                    ),
                ),
                (
                    "porcentagem_desconto",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Porcentagem de Desconto"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado Em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Última Alteração"
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmacia.medicamento",
                        verbose_name="Medicamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_positivos",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Feedbacks Positivos"
                    ),
                ),
                (
                    "feedback_negativos",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Feedbacks Negativos"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado Em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Última Alteração"
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmacia.medicamento",
                        verbose_name="Medicamento",
                    ),
                ),
            ],
        ),
    ]
