# Generated by Django 4.1.5 on 2023-02-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0003_alter_preco_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="farmacia", name="cep",),
        migrations.RemoveField(model_name="farmacia", name="endereco",),
        migrations.RemoveField(model_name="farmacia", name="latitude_cep",),
        migrations.RemoveField(model_name="farmacia", name="longitude_cep",),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=250, verbose_name="CEP")),
                ("endereco", models.CharField(max_length=250, verbose_name="Endereço")),
                ("latitude_cep", models.FloatField(verbose_name="Latitude")),
                ("longitude_cep", models.FloatField(verbose_name="Longitude")),
                (
                    "farmacia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="farmacia.farmacia",
                        verbose_name="Fármacia",
                    ),
                ),
            ],
        ),
    ]
