# Generated by Django 4.1.5 on 2023-02-07 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250, verbose_name="Nome")),
                ("cpf", models.CharField(max_length=250, verbose_name="CPF")),
                (
                    "hash_senha",
                    models.CharField(
                        max_length=250, verbose_name="Senha Criptografada"
                    ),
                ),
                ("email", models.EmailField(max_length=250, verbose_name="email")),
                (
                    "data_nascimento",
                    models.DateField(max_length=150, verbose_name="Data de Nascimento"),
                ),
                ("celular", models.CharField(max_length=250, verbose_name="Celular")),
                (
                    "numero_colaboracoes",
                    models.IntegerField(verbose_name="Número de Colaborações"),
                ),
                ("notificacoes", models.BooleanField(verbose_name="Notificações?")),
                ("tipo_usuario", models.IntegerField(verbose_name="Tipo de Usuário")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registrado Em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Alteração"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pesquisa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filtro_aplicado",
                    models.CharField(max_length=500, verbose_name="Filtro Aplicado"),
                ),
                (
                    "item_pesquisado",
                    models.CharField(max_length=500, verbose_name="Item Pesquisado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado Em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Alteração"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.usuario",
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endereco", models.CharField(max_length=250, verbose_name="Endereço")),
                ("latitude_cep", models.FloatField(verbose_name="Latitude CEP")),
                ("longitude_cep", models.FloatField(verbose_name="Longitude CEP")),
                ("cep", models.CharField(max_length=250, verbose_name="CEP")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuario.usuario",
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
    ]
